version: "3"
services:
  user-service:
    build: .
    image: user-service:latest
    ports:
      - "8086:8080"
    env_file:
      - ../kdrive.env
    depends_on:
      - spike-service
  spike-service:
    image: spike-service:latest
    ports:
      - "8080:8080"
    env_file:
      - ../kdrive.env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
